### ISSUE TITLE
Some details?

### ISSUE THREAD

**Issue by jiayily** [DRL-CASIA/MVM3D#7]
Hi, after reading your paper, I have some doubts as following:
(1) How to predefine orientation in feature perspective pooling? This prior does't seem trivial. 
(2) After predicting orientation under each view, we should transform it to the bev space before nms?
(3) The last term in PPN loss.  How to obtain the ground-truth 2d bounding box in the image space? 
(4) Why use the first term in MBON loss? The predicted bounding box in each perspective is also obtained by projection?
Looking forward to your reply. Thank you.

**Comment by ZichengDuan** [comment]
Hi Jiayi, 
Thank you for your interest in our paper, please see our responses below regarding your questions.



**1. How to predefine orientation in feature perspective pooling? This prior doesn't seem trivial.**

The “predefined orientation” in our paper could be interpreted as “zero degrees in birds-eye-view space” or a “without rotation”.




**2. After predicting orientation under each view, we should transform it to the BEV space before NMS?**

​No, transforming the predicted orientation into BEV space before NMS is not necessary. The predicted object location, orientation and confidences will be output together as a final result after NMS. t’s recommended that you do the transformation before visualization.




**3. The last term in PPN loss. How to obtain the ground-truth 2d bounding box in the image space?**

The ground truth 2D bounding boxes of each object in each view are provided in the dataset.




**4. Why use the first term in MBON loss? The predicted bounding box in each perspective is also obtained by projection?**
 
1) The first term of MBON loss calculates the per-view losses between the predicted objectiveness of the objects and the ground truth labels. Note that this is similar to the loss calculation in PPN loss, however, this calculation focuses on per-view objectiveness loss. This loss term helps supervise the training.
 2) Yes, the predicted 2D boxes are obtained from the projection of generated 3D boxes.

> Hi, after reading your paper, I have some doubts as following: (1) How to predefine orientation in feature perspective pooling? This prior does't seem trivial. (2) After predicting orientation under each view, we should transform it to the bev space before nms? (3) The last term in PPN loss. How to obtain the ground-truth 2d bounding box in the image space? (4) Why use the first term in MBON loss? The predicted bounding box in each perspective is also obtained by projection? Looking forward to your reply. Thank you.
