### ISSUE TITLE
where is  "persp_trans_detector.py"

### ISSUE THREAD

**Issue by anzisheng** [DRL-CASIA/MVM3D#9]
when I run python infer.py , I run across an error:
"ModuleNotFoundError: No module named 'codes.models.persp_trans_detector'"
where is the "persp_trans_detector.py"?

**Comment by ZichengDuan** [comment]
Hi, I have fixed the wrong import path in infer.py. It should be `codes.models.PPN` instead of  `codes.models.persp_trans_detector`, thanks for pointing out.
